// Templates emitted by `applens init`.

/// The tool config written to `qa_graph/applens.yaml`. The `permissions:` list
/// is pre-granted by `applens run` at session start (adb / simctl), so native
/// dialogs never appear in CI (ARCHITECTURE.md §7/§10).
const String applensYamlTemplate = '''
# AppLens configuration. See docs/ARCHITECTURE.md.
app_id: com.example.app # the device applicationId / bundle id, for permission pre-grants.
device_profiles:
  - { device: pixel6, locale: en, theme: light }
strategies: [smoke, regression]
permissions: [] # e.g. android.permission.CAMERA — pre-granted by `applens run`.
modules: {} # optional explicit file->module map for impact analysis.
module_paths: {} # optional module->source globs, e.g. {shop: [lib/shop/**]}; scopes `applens triage` git correlation.
''';

/// The generated `integration_test/applens_entry.dart`. It hosts the runner with
/// a NavigatorObserver for route identity and drives the app via the first-party
/// engine — Tier-0 integration, no production code touched (ARCHITECTURE.md §10).
const String entrypointTemplate = '''
// GENERATED by `applens init`. Hosts the AppLens runner on the app under test.
// Complete the two TODOs, then run on a device: applens run qa_graph
import 'package:applens_core/applens_core.dart';
import 'package:applens_runner/applens_runner.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
// TODO(applens) 1: import your app, e.g.
// import 'package:my_app/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  final observer = AppLensNavigatorObserver();

  testWidgets('applens walk', (tester) async {
    // TODO(applens) 2: launch your app with the AppLens observer installed so
    // route identity is observable, e.g.
    // await tester.pumpWidget(app.MyApp(navigatorObservers: [observer]));
    await tester.pumpAndSettle();

    final driver = AppLensWidgetDriver(tester);
    final orchestrator = Orchestrator(
      driver: driver,
      fingerprints: WidgetFingerprintSource(driver, observer),
      store: SqliteRunStore.open('build/applens/run.db'),
    );

    final graph = loadGraph('qa_graph');
    // `applens plan qa_graph` compiles the plan the host bundles for this run.
    // await orchestrator.run(graph, plan);
    expect(graph.nodes, isNotEmpty);
  });
}
''';

/// A starter module so a fresh graph validates and renders.
const String starterModuleManifest = '''
owner: team-app
tags: [smoke]
entry_nodes: [home]
''';

/// A single starter node.
const String starterNode = '''
identity:
  route: /
  anchors: [app_root]
payload:
  assertions:
    - { type: widget_exists, key: app_root }
  edges: []
  tags: [smoke]
''';
