import 'package:applens_core/applens_core.dart';
import 'package:test/test.dart';

/// A test-local guard standing in for the Session-8 baseline-only guard, used
/// to exercise the [MergeGuard] contract shape.
class _BaselineOnlyGuard implements MergeGuard {
  @override
  bool permits(Iterable<String> changedPaths) => changedPaths.every(
        (path) => path.contains('visual_baselines') || path.endsWith('.png'),
      );
}

void main() {
  group('VCS contract value types', () {
    test('PrDraft carries its fields with a default base branch', () {
      const draft = PrDraft(
        title: 'Approve baseline order.confirm',
        body: 'Auto-generated by triage.',
        headBranch: 'applens/baseline-order-confirm',
      );
      expect(draft.baseBranch, 'main');
      expect(draft.labels, isEmpty);
    });

    test('MergeResult.merged reflects the outcome', () {
      const ok = MergeResult(MergeOutcome.merged);
      const no = MergeResult(
        MergeOutcome.guardRejected,
        detail: 'touched assertions',
      );
      expect(ok.merged, isTrue);
      expect(no.merged, isFalse);
      expect(no.detail, contains('assertions'));
    });

    test('a MergeGuard is a deterministic predicate over changed paths', () {
      final guard = _BaselineOnlyGuard();
      expect(
        guard.permits([
          'qa_graph/visual_baselines/order.confirm.yaml',
          'qa_graph/goldens/order_confirm.png',
        ]),
        isTrue,
      );
      expect(guard.permits(['lib/order_button.dart']), isFalse);
    });
  });
}
